language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer config -a -g http-basic.repo.magento.com $COMPOSER_MAGENTO_USERNAME $COMPOSER_MAGENTO_PASSWORD
  - composer install --ignore-platform-reqs

script:
  - vendor/bin/phpcs --runtime-set installed_paths vendor/magento/marketplace-eqp --standard=MEQP2 src
  - vendor/bin/phpstan --level=7 analyse src
