language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer config -a -g http-basic.repo.magento.com $COMPOSER_MAGENTO_USERNAME $COMPOSER_MAGENTO_PASSWORD
  - composer install --ignore-platform-reqs

script:
  - vendor/bin/phpcs --runtime-set installed_paths vendor/magento/marketplace-eqp --standard=MEQP2 src
  - php -d display_errors=1 vendor/bin/phpstan analyse --level=7 -c phpstan.neon src

cache:
  - $HOME/.composer
  - $HOME/.cache/composer
